version: "3.9"

services:
  compute_service:
    build:
      context: .
      dockerfile: cmd/compute_service/Dockerfile
    ports:
      - "50051:50051"

  calc_service:
    build:
      context: .
      dockerfile: cmd/calc_service/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - compute_service