version: "3.8"

services:
  compute_service:
    build:
      context: .
      dockerfile: Dockerfile.compute
    ports:
      - "50051:50051"
    networks:
      - app_network

  calc_service:
    build:
      context: .
      dockerfile: Dockerfile.calc
    ports:
      - "8080:8080"
    environment:
      - GRPC_ADDRESS=compute_service:50051
    depends_on:
      - compute_service
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
